---
- type: replace
  path: /instance_groups/name=locker/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((routing-nats-deployment))
    properties:
      route_registrar:
        routes:
        - name: locker
          port: 8910
          tags:
            component: locker
          registration_interval: 10s
          uris:
          - ((locker-uri))

- type: remove
  path: /instance_groups/name=locker/networks/name=default/static_ips

- type: remove
  path: /instance_groups/name=locker/jobs/name=locker/properties/locker/ssl_cert

- type: remove
  path: /instance_groups/name=locker/jobs/name=locker/properties/locker/ssl_key

- type: remove
  path: /variables/name=locker-ca

- type: remove
  path: /variables/name=locker-tls

- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.161.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.161.0
    sha1: 05a4c2c7eac94dca40fb622cc936b8f0271ca04f
