name: locker

instance_groups:
- name: locker
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 1GB
  networks:
  - name: default
    static_ips:
    - ((locker-static-ip))
  jobs:
  - name: locker
    release: locker
    properties:
      locker:
        user: locker
        password: ((locker-password))
        ssl_cert: ((locker-tls.certificate))
        ssl_key: ((locker-tls.private_key))

variables:
- name: locker-password
  type: password
- name: locker-ca
  type: certificate
  options:
    is_ca: true
    common_name: lockerCA
- name: locker-tls
  type: certificate
  options:
    ca: locker-ca
    common_name: locker
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - ((locker-static-ip))

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: locker
  version: 0.2.1
  url: https://github.com/cloudfoundry-community/locker-boshrelease/releases/download/v0.2.1/locker-0.2.1.tgz
  sha1: ccfcc48d63555a3733c3594d9429a5c1875a9dd2
