---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

releases:
- name: locker
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
  - name: locker
    jobs:
    - name: locker
      release: locker
    instances: 1
    persistent_disk: 1024
    stemcell: ubuntu
    vm_type: small
    networks:
    - name: locker
      static_ips: (( static_ips(0) ))

properties:
  locker:
    user: locker
    password: (( param "Please configure a password for locker" ))
    # ssl_cert: |+
    #   YOUR_SSL_CERT_HERE
    # ssl_key: |+
    #   YOUR_SSL_KEY_HERE
