---
meta:
  name: locker
  target: sw
  url:     https://ci.starkandwayne.com
  aws:
    bucket: locker-boshrelease-pipeline # re-use old ci bucket after boshrelease rename
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  github:
    owner: cloudfoundry-community
    repo:  locker-boshrelease
    private_key:  (( vault "secret/pipelines/locker-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/locker-boshrelease/github:token" ))
  bosh-lite:
    target: https://10.58.111.46:25555
    deployment: locker-warden
  slack:
    webhook: (( vault "secret/pipelines/locker-boshrelease/slack:webhook" ))
    channel: "#botspam"
